let
    DataMin = #date(2018, 1, 1),
    DataMax = #date(2069, 12, 31),
    QtdeDias = Duration.Days(DataMax-DataMin)+1,
    Personalizar1 = List.Dates(DataMin, QtdeDias, #duration(1,0,0,0)),
    #"Convertido para Tabela" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data"}}),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Ano Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Ano", each Date.Year([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
    #"Colunas Mescladas" = Table.CombineColumns(Table.TransformColumnTypes(#"Mês Inserido", {{"Ano", type text}}, "pt-BR"),{"Nome do Mês", "Ano"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"Mês-Ano"),
    #"Ano Inserido1" = Table.AddColumn(#"Colunas Mescladas", "Ano", each Date.Year([Data]), Int64.Type),
    #"Linhas Classificadas" = Table.Sort(#"Ano Inserido1",{{"Mês-Ano", Order.Ascending}}),
    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Classificadas", "Personalizar", each [Ano]*100+[Mês]),
    #"Linhas Classificadas1" = Table.Sort(#"Personalização Adicionada",{{"Data", Order.Ascending}}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Linhas Classificadas1",{{"Personalizar", Int64.Type}}),
    #"Linhas Classificadas2" = Table.Sort(#"Tipo Alterado1",{{"Personalizar", Order.Ascending}}),
    #"Personalização Adicionada1" = Table.AddColumn(#"Linhas Classificadas2", "Mês Abrev", each Date.ToText([Data],"MMM")),
    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Personalização Adicionada1", "Mesclado", each Text.Combine({[Mês Abrev], "-", Text.From([Ano], "pt-BR")}), type text),
    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Mesclada Inserida",{"Mês-Ano"}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas",{{"Mesclado", "Mês e Ano"}, {"Personalizar", "Ano Mês Class"}}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Ano Mês Class", type text}}),
    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado2", each [Data] <> null and [Data] <> ""),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Linhas Filtradas", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Semana do Mês Inserida" = Table.AddColumn(#"Semana do Ano Inserida", "Semana do Mês", each Date.WeekOfMonth([Data]), Int64.Type),
    #"Dia da Semana Inserido" = Table.AddColumn(#"Semana do Mês Inserida", "Dia da Semana", each Date.DayOfWeek([Data]), Int64.Type)
in
    #"Dia da Semana Inserido"