let
    Fonte = Table.SelectColumns(SharePoint.Contents("https://prodeboffice365.sharepoint.com/sites/EquipedeMonitoramentoCAJ", [ApiVersion = 15]){[Name="Programao"]}[Content]{[Name="Luciano_Reis"]}[Content]{[Name="POWER BI"]}[Content]{[Name="Dados Power BI"]}[Content]{[Name="Controle de Dispensa"]}[Content],{"Content"}),
    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte,{"Content"}),
    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(#"Outras Colunas Removidas", each [Attributes]?[Hidden]? <> true),
    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (2)", each #"Transformar Arquivo (2)"([Content])),
    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Invocar Função Personalizada1", {"Transformar Arquivo (2)"}),
    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (2)", Table.ColumnNames(#"Transformar Arquivo (2)"(#"Arquivo de Amostra (2)"))),
    #"Texto Aparado2" = Table.TransformColumns(#"Coluna de Tabela Expandida1",{{"Column1", Text.Trim, type text}, {"Column2", Text.Trim, type text}, {"Column3", Text.Trim, type text}, {"Column4", Text.Trim, type text}, {"Column5", Text.Trim, type text}, {"Column6", Text.Trim, type text}, {"Column7", Text.Trim, type text}, {"Column8", Text.Trim, type text}, {"Column9", Text.Trim, type text}, {"Column10", Text.Trim, type text}, {"Column11", Text.Trim, type text}, {"Column12", Text.Trim, type text}, {"Column13", Text.Trim, type text}, {"Column14", Text.Trim, type text}, {"Column15", Text.Trim, type text}, {"Column16", Text.Trim, type text}, {"Column17", Text.Trim, type text}, {"Column18", Text.Trim, type text}, {"Column19", Text.Trim, type text}, {"Column20", Text.Trim, type text}, {"Column21", Text.Trim, type text}, {"Column22", Text.Trim, type text}, {"Column23", Text.Trim, type text}, {"Column24", Text.Trim, type text}, {"Column25", Text.Trim, type text}}),
    #"Texto Limpo3" = Table.TransformColumns(#"Texto Aparado2",{{"Column1", Text.Clean, type text}, {"Column2", Text.Clean, type text}, {"Column3", Text.Clean, type text}, {"Column4", Text.Clean, type text}, {"Column5", Text.Clean, type text}, {"Column6", Text.Clean, type text}, {"Column7", Text.Clean, type text}, {"Column8", Text.Clean, type text}, {"Column9", Text.Clean, type text}, {"Column10", Text.Clean, type text}, {"Column11", Text.Clean, type text}, {"Column12", Text.Clean, type text}, {"Column13", Text.Clean, type text}, {"Column14", Text.Clean, type text}, {"Column15", Text.Clean, type text}, {"Column16", Text.Clean, type text}, {"Column17", Text.Clean, type text}, {"Column18", Text.Clean, type text}, {"Column19", Text.Clean, type text}, {"Column20", Text.Clean, type text}, {"Column21", Text.Clean, type text}, {"Column22", Text.Clean, type text}, {"Column23", Text.Clean, type text}, {"Column24", Text.Clean, type text}, {"Column25", Text.Clean, type text}}),
    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Texto Limpo3", [PromoteAllScalars=true]),
    #"Linhas Filtradas" = Table.SelectRows(#"Cabeçalhos Promovidos", each ([#"Origem CI"] <> "Diretoria" and [#"Origem CI"] <> "Núcleo AF Básica" and [#"Origem CI"] <> "Núcleo de RP" and [#"Origem CI"] <> "Secretaria")),
    TipoAlterado = Table.TransformColumnTypes(#"Linhas Filtradas",{{"Data CI", type date}}),
    #"Texto Aparado1" = Table.TransformColumns(TipoAlterado,{{"Medicamento", Text.Trim, type text}}),
    #"Texto Limpo2" = Table.TransformColumns(#"Texto Aparado1",{{"Medicamento", Text.Clean, type text}}),
    De = List.Buffer(Dicionário[De]),
    Para = List.Buffer(Dicionário[Para]),
    Nome_Corrigido = Table.TransformColumns(#"Texto Limpo2", {"Medicamento", each Fn_De_Para(_, De , Para), type text}), 
      
    
    #"Colunas Removidas1" = Table.RemoveColumns(Nome_Corrigido,{"Documento", "Fornecedor", "Fabricante", "Produto/Serviço", "Data Pesquisa", "Preço Referência", "PMVG", "Inciso", "Classificação", "Preço Final", "Data Solicitação Proposta", "Nº Dispensa", "Ano Dispensa"}),
    #"Linhas Filtradas2" = Table.SelectRows(#"Colunas Removidas1", each true),
    PAOE = Table.SelectRows(#"Linhas Filtradas2", each Text.Contains([#"PAOE"], "6063") or Text.Contains([#"PAOE"], "4256") or Text.Contains([#"PAOE"], "4256")),
    #"Tipo Alterado1" = Table.TransformColumnTypes(PAOE,{{"Medicamento", type text}, {"Quantidade", Int64.Type}, {"Status CI", type text}, {"N° Processo", type text}}),
    #"Erros Removidos1" = Table.RemoveRowsWithErrors(#"Tipo Alterado1", {"Quantidade"}),
    #"Erros Removidos" = Table.RemoveRowsWithErrors(#"Erros Removidos1", {"Medicamento"}),
    #"Linhas Classificadas" = Table.Sort(#"Erros Removidos",{{"Medicamento", Order.Descending}}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas Classificadas",{{"N° Processo", type text}}),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado2",{{"N° Processo", "Processo SEI"}}),
    #"Texto Limpo" = Table.TransformColumns(#"Colunas Renomeadas2",{{"Processo SEI", Text.Clean, type text}}),
    #"Texto Aparado" = Table.TransformColumns(#"Texto Limpo",{{"Processo SEI", Text.Trim, type text}, {"Medicamento", Text.Trim, type text}}),
    #"Texto Limpo1" = Table.TransformColumns(#"Texto Aparado",{{"Medicamento", Text.Clean, type text}}),
    #"Linhas Filtradas3" = Table.SelectRows(#"Texto Limpo1", each ([Processo SEI] <> "")),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Linhas Filtradas3",{"", "_1"}),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Colunas Removidas2",{{"Nº CI", "Código CI"}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Renomeadas4","00/00/0000","",Replacer.ReplaceText,{"Data Conclusão Dispensa"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído",{{"Data Conclusão Dispensa", type date}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"Processo SEI"}, #"Controle de Aquisicao", {"Processo SEI"}, "Controle de Aquisicao", JoinKind.LeftOuter),
    #"Controle de Aquisicao Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Controle de Aquisicao", {"Nº AFM", "Data de Convocação para Assinatura", "Data Assinatura AFM", "Quantidade Entregue"}, {"Nº AFM", "Data de Convocação para Assinatura", "Data Assinatura AFM", "Quantidade Entregue"}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Controle de Aquisicao Expandido","00/00/0000","",Replacer.ReplaceText,{"Data de Convocação para Assinatura"}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Valor Substituído1",{{"Data de Convocação para Assinatura", type date}}),
    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado3", {"Código CI", "Medicamento", "Quantidade", "Processo SEI"})
in
    #"Duplicatas Removidas"