let
    Fonte = Excel.Workbook(SharePoint.Contents("https://prodeboffice365.sharepoint.com/sites/EquipedeMonitoramentoCAJ", [ApiVersion = 15]){[Name="Programao"]}[Content]{[Name="Luciano_Reis"]}[Content]{[Name="POWER BI"]}[Content]{[Name="Dados Power BI"]}[Content]{[Name="Deposito judicial.xlsx"]}[Content]){[Name="Tabela1"]}[Data],
    #"Texto Aparado" = Table.TransformColumns(Fonte,{{"Número do processo", Text.Trim, type text}, {"Interessado", Text.Trim, type text}, {"Ação Judicial", Text.Trim, type text}, {"Medicamento", Text.Trim, type text}, {" ESTOQUE", Text.Trim, type text}, {"Unidade Dispensadora", Text.Trim, type text}, {"Status", Text.Trim, type text}, {"SEI", Text.Trim, type text}}),
    #"Texto Limpo" = Table.TransformColumns(#"Texto Aparado",{{"Número do processo", Text.Clean, type text}, {"Interessado", Text.Clean, type text}, {"Ação Judicial", Text.Clean, type text}, {"Medicamento", Text.Clean, type text}, {" ESTOQUE", Text.Clean, type text}, {"Unidade Dispensadora", Text.Clean, type text}, {"Status", Text.Clean, type text}, {"SEI", Text.Clean, type text}}),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Texto Limpo",{{"Interessado", Text.Upper, type text}, {"Medicamento", Text.Upper, type text}, {"Unidade Dispensadora", Text.Upper, type text}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Texto em Maiúscula",{{"Número do processo", type text}, {"Data Entrada", type date}, {"Interessado", type text}, {"Ação Judicial", type text}, {"Medicamento", type text}, {" ESTOQUE", type text}, {"Unidade Dispensadora", type text}, {"Status", type text}, {"Quantidade Autorizada", Int64.Type}, {"Frequência (em dias)", Int64.Type}, {"Período de tratamento (em meses)", Int64.Type}, {"Data do depósito", type date}, {"Cobertura do depósito (dias)", Int64.Type}, {"Data do próximo atendimento", type date}, {"SEI", type text}, {"Valor depositado", type number}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{" ESTOQUE", "Unidade Dispensadora", "Status", "Quantidade Autorizada", "Frequência (em dias)", "Período de tratamento (em meses)", "Cobertura do depósito (dias)"})
in
    #"Colunas Removidas"