let
    Fonte = Table.SelectColumns(SharePoint.Contents("https://prodeboffice365.sharepoint.com/sites/EquipedeMonitoramentoCAJ", [ApiVersion = 15]){[Name="Programao"]}[Content]{[Name="Luciano_Reis"]}[Content]{[Name="POWER BI"]}[Content]{[Name="Dados Power BI"]}[Content]{[Name="Lista de medicamentos"]}[Content],{"Content"}),
    #"Invocar Função Personalizada1" = Table.AddColumn(Fonte, "Transformar Arquivo (4)", each #"Transformar Arquivo (4)"([Content])),
    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Invocar Função Personalizada1", {"Transformar Arquivo (4)"}),
    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (4)", Table.ColumnNames(#"Transformar Arquivo (4)"(#"Arquivo de Amostra (23)"))),
    #"Tipo Alterado7" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"CÓDIGO SIMPAS", type text}}),
    #"Texto Aparado" = Table.TransformColumns(#"Tipo Alterado7",{{"CÓDIGO SIMPAS", Text.Trim, type text}}),
    #"Texto Limpo" = Table.TransformColumns(#"Texto Aparado",{{"CÓDIGO SIMPAS", Text.Clean, type text}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Texto Limpo", {"CÓDIGO SIMPAS"}, #"Ata RP", {"CÓDIGO SIMPAS"}, "Ata RP", JoinKind.LeftOuter),
    #"Ata RP Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Ata RP", {"Fator Embalagem", "Valor Unitário", "Fornecedor", "CNPJ", "Rp Ativo", "Marca", "Saldo", "Licitaçao", "Validade Ata"}, {"Fator Embalagem.1", "Valor Unitário", "Fornecedor", "CNPJ", "Rp Ativo", "Marca", "Saldo", "Licitaçao", "Validade Ata"}),
    #"Consultas Mescladas1" = Table.NestedJoin(#"Ata RP Expandido", {"CURVA"}, #"Parametros do pedido", {"Curva"}, "Parametros do pedido", JoinKind.LeftOuter),
    #"Parametros do pedido Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "Parametros do pedido", {"Fator"}, {"Fator"}),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Parametros do pedido Expandido",{{"MEDICAMENTO", "Medicamento"}}),
    #"Duplicatas Removidas" = Table.Distinct(#"Colunas Renomeadas4", {"Medicamento"}),
    #"Linhas Classificadas" = Table.Sort(#"Duplicatas Removidas",{{"Medicamento", Order.Descending}}),
    #"Linhas Classificadas1" = Table.Sort(#"Linhas Classificadas",{{"Medicamento", Order.Descending}}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas Classificadas1",{{"Fator Embalagem.1", Int64.Type}}),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Tipo Alterado2",{{"Fator Embalagem.1", "Fator Embalagem-1"}, {"FATOR EMBALAGEM", "FATOR EMBALAGEM-2"}}),
    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Colunas Renomeadas2", "FATOR EMBALAGEM", each if [#"Fator Embalagem-1"] <> null then [#"Fator Embalagem-1"] else [#"FATOR EMBALAGEM-2"]),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Coluna Condicional Adicionada1",{"Medicamento", "CÓDIGO SIMPAS", "CURVA", "Indicação Terapêutica", "Tempo de Tratamento", "Responsável", "FATOR EMBALAGEM-2", "Fator Embalagem-1", "FATOR EMBALAGEM", "Fornecedor", "Marca", "Saldo", "Licitaçao", "Validade Ata", "Rp Ativo", "Fator"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas",{"Fator Embalagem-1", "FATOR EMBALAGEM-2"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas2", each true),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"CÓDIGO SIMPAS", type text}}),
    #"Consultas Mescladas2" = Table.NestedJoin(#"Tipo Alterado3", {"CÓDIGO SIMPAS"}, #"Monitoramento RP", {"SIMPAS"}, "Monitoramento RP", JoinKind.LeftOuter),
    #"Monitoramento RP Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "Monitoramento RP", {"N° PROCESSO", "ANDAMENTO", "Prazo para ativação, caso logre Êxito"}, {"N° PROCESSO", "ANDAMENTO", "Prazo para ativação, caso logre Êxito"}),
    #"Duplicatas Removidas2" = Table.Distinct(#"Monitoramento RP Expandido", {"Medicamento", "CÓDIGO SIMPAS"}),
    #"Colunas Renomeadas3" = Table.RenameColumns(#"Duplicatas Removidas2",{{"Prazo para ativação, caso logre Êxito", "Prazo para ativação"}}),
    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Colunas Renomeadas3",{{"Medicamento", type text}}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado4", each true),
    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Filtradas1",null,"Sem previsão",Replacer.ReplaceValue,{"Prazo para ativação"}),
    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído",null,"",Replacer.ReplaceValue,{"Rp Ativo"}),
    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído1", each true),
    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Linhas Filtradas2",{{"Tipo", type text}}),
    #"Linhas Filtradas3" = Table.SelectRows(#"Tipo Alterado5", each ([STATUS] = "ATIVO")),
    #"Valor Substituído3" = Table.ReplaceValue(#"Linhas Filtradas3","","Não",Replacer.ReplaceValue,{"Rp Ativo"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído3",{{"PREÇO", type number}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Valor Unitário", "Custo em rp"}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"Column14", "Column15", "Column16", "N° PROCESSO"})
in
    #"Colunas Removidas"